import Head from 'next/head'
import { useRouter } from 'next/router'
import { useGetProfileQuery } from '../../services/profiles'
import Avatar from '../../components/Avatar'
import { pick_random_status } from '../../utils/random_status'
import ProfileStatus from '../../components/ProfileStatus'
import Tabs from '../../components/Tabs'
import InfoContent from '../../components/InfoContent'

import styles from '../../styles/pages/profile.module.scss'

export default function ProfileDetails() {
  const router = useRouter()
  const { id } = router.query

  const { data: profile, error, isLoading } = useGetProfileQuery(id)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        {isLoading || !profile ? (
          'loading'
        ) : error ? (
          error
        ) : (
          <div>
            <div>
              <Avatar
                image={profile?.img}
                alt={profile?.first_name}
                size={`lg`}
                available={profile?.available}
              />
            </div>
            <div className={styles.name}>
              {profile?.first_name} {profile?.lastName}
            </div>
            <ProfileStatus text={pick_random_status(profile)} />

            <div>
              <Tabs
                elements={[
                  {
                    title: 'Info',
                    content: <InfoContent profile={profile} />,
                  },
                  { title: 'Photos', content: <div>photos</div> },
                ]}
              />
            </div>
          </div>
        )}
      </div>
    </>
  )
}
