import Head from 'next/head'
import Button from '../library/Button'

import { useGetAllProfilesQuery } from '../services/profiles'

export default function Home() {
  const { data, error, isLoading } = useGetAllProfilesQuery()
  console.log(error)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Friends</h1>

      <div>
        <Button>Hello world</Button>
        <div>
          {isLoading ? (
            'loading'
          ) : error ? (
            <div>{error}</div>
          ) : (
            <div>
              {data?.map((profile) => (
                <div key={profile.id}>
                  <div>
                    {profile.first_name} {profile.last_name}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
